# Generated by Django 3.2 on 2022-11-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('brightness', 'Brightness'), ('earlybird', 'Earlybird'), ('sparkle', 'Sparkle'), ('inkwell', 'Inkwell'), ('awesome', 'Awesome'), ('mystyle', 'MyStyle'), ('normal', 'Normal'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('strange', 'Strange'), ('beautiful', 'beautiful'), ('zest', 'zest')], default='normal', max_length=32),
        ),
    ]
